### ISSUE TITLE
ARIA Automation: A Demonstration of AT-Driver

### ISSUE THREAD

**Issue by lolaodelola** [w3c/breakouts-day-2024#23]
### Session description

See how the AT-Driver spec is implemented to facilitate automated tests for assistive technologies.

### Session goal

To show interested parties how AT-Driver can be implemented.

### Session type

Breakout (Default)

### IRC channel (Optional)

#aria-automation

### Link to calendar (Optional)

[Calendar entry](https://www.w3.org/events/meetings/35ed70c7-c894-46ae-b2f7-a29696eebe31/)

**Comment by tidoust** [comment]
Breakout session canceled per proposer request. Closing the issue accordingly. Many thanks for proposing the session, @lolaodelola!
