### ISSUE TITLE
[CSS] Anchor Positioning

### ISSUE THREAD

**Issue by tabatkins** [w3c/breakouts-day-2024#8]
### Session description

Discuss contentious/important issues with the [CSS Anchor Position spec](https://drafts.csswg.org/css-anchor-position/).

Notably, the new "style interleaving" concept that it shares with Container Queries, and the 'position-animation' proposal.

### Session goal

Come to consensus on issues

### Session type

Breakout (Default)

### Additional session chairs (Optional)

@fantasai

### IRC channel (Optional)

#css

### Instructions for meeting planners (Optional)

Avoid conflicts with other CSS-related topics

### Link to calendar (Optional)

[Calendar entry](https://www.w3.org/events/meetings/9c5c12b5-ccdb-42c7-a98a-ae766e1d416a/)

**Comment by ianbjacobs** [comment]
Breakout session canceled per proposer request. Closing the issue accordingly. Many thanks for proposing the session, @tabatkins!
